# Generated by Django 2.0.2 on 2018-03-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperTraderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='closing',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='high',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='low',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='opening',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='volume',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
