# Generated by Django 2.0.2 on 2018-04-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperTraderApp', '0002_auto_20180324_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.CharField(max_length=99999999999)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='stockmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='closing',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='opening',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='symbol',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='volume',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
