# Generated by Django 2.0.2 on 2018-04-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperTraderApp', '0006_adminstockmodel_symb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
