# Generated by Django 2.0.2 on 2018-04-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperTraderApp', '0009_auto_20180416_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='user',
            field=models.CharField(default='null', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='stocks',
            field=models.CharField(max_length=99999),
        ),
    ]
